const palavras = [
 // Animais
 "ABELHA", "AGUIA", "ALCE", "ARANHA", "BALEIA", "BORBOLETA", "CABRA", "CACHORRO", 
 "CAMELO", "CANARIO", "CAPIVARA", "CARANGUEJO", "CASTOR", "CAVALO", "CHIMPANZE", 
 "COBRA", "COELHO", "CORUJA", "CROCODILO", "DINOSSAURO", "ELEFANTE", "ESCORPIAO", 
 "ESQUILO", "FOCA", "FORMIGA", "FRAGATA", "GAFANHOTO", "GALINHA", "GALO", "GAMBA", 
 "GATO", "GAVIAO", "GIRAFA", "GORILA", "GUAXINIM", "HAMSTER", "HIENA", "HIPOPOTAMO",
 "IGUANA", "JACARE", "JAGUATIRICA", "JUMENTO", "KIWI", "LAGARTA", "LAGARTO", "LEAO", 
 "LEOPARDO", "LOBO", "LONTRA", "MACACO", "MAMUTE", "MOSCA", "MOSQUITO", "OVELHA", 
 "PANDA", "PAPAGAIO", "PATO", "PEIXE", "PELICANO", "PINGÜIM", "POLVO", "PORCO", 
 "RAPOSA", "RATO", "RINOCERONTE", "SALAMANDRA", "SAPO", "TARTARUGA", "TIGRE", "TOURO", 
 "TUCANO", "URSO", "VACA", "VESPA", "ZEBRA",
 
 // Frutas
 "ABACATE", "ABACAXI", "ACEROLA", "AMEIXA", "AMORA", "BANANA", "CACAU", "CAJU", 
 "CARAMBOLA", "CEREJA", "COCO", "DAMASCO", "FIGO", "FRAMBOESA", "GOIABA", "GROSELHA", 
 "JABUTICABA", "JACA", "KIWI", "LARANJA", "LIMAO", "LICHIA", "MANGA", "MARACUJA", 
 "MELANCIA", "MELAO", "MORANGO", "PERA", "PESSEGO", "PITANGA", "ROMÃ", "TANGERINA", 
 "UVA",
 
 // Países
 "ALBANIA", "ALEMANHA", "ARGENTINA", "AUSTRALIA", "BAHAMAS", "BANGLADESH", "BELGICA", 
 "BOLIVIA", "BRASIL", "BULGARIA", "CANADA", "CHILE", "CHINA", "COLOMBIA", "CROACIA", 
 "CUBA", "DINAMARCA", "EGITO", "EQUADOR", "ESPANHA", "ESTONIA", "ETIOPIA", "FINLANDIA", 
 "FRANÇA", "GRECIA", "HAITI", "HOLANDA", "HUNGRIA", "INDIA", "INDONESIA", "IRAQUE", 
 "IRLANDA", "ISLANDIA", "ISRAEL", "ITALIA", "JAMAICA", "JAPAO", "JORDANIA", "KUWAIT", 
 "LIBANO", "LIBIA", "LUXEMBURGO", "MADAGASCAR", "MALASIA", "MARROCOS", "MEXICO", 
 "MONACO", "MONGOLIA", "NEPAL", "NIGERIA", "NORUEGA", "PANAMA", "PAQUISTAO", "PERU", 
 "POLONIA", "PORTUGAL", "QATAR", "QUENIA", "ROMENIA", "RUSSIA", "SENEGAL", "SERVIA", 
 "SUECIA", "SUIÇA", "TAILANDIA", "TAIWAN", "TURQUIA", "UCRANIA", "URUGUAI", "VENEZUELA", 
 "VIETNA", "ZAMBIA", "ZIMBABUE",
 
 // Profissões
 "ADVOGADO", "AGRICULTOR", "ARQUITETO", "ARTISTA", "ASTRONAUTA", "ATLETA", "ATOR", 
 "BAILARINO", "BANQUEIRO", "BARBEIRO", "BIBLIOTECARIO", "BIOLOGO", "BOMBEIRO", 
 "CABELEIREIRO", "CANTOR", "CARPINTEIRO", "CARTEIRO", "CIENTISTA", "CINEASTA", 
 "COZINHEIRO", "DENTISTA", "DESIGNER", "DETETIVE", "ECONOMISTA", "ELETRICISTA", 
 "EMPRESARIO", "ENFERMEIRO", "ENGENHEIRO", "ESCRITOR", "ESCULTOR", "FARMACEUTICO", 
 "FISIOTERAPEUTA", "FOTOGRAFO", "GARÇOM", "GEOLOGO", "HISTORIADOR", "JARDINEIRO", 
 "JORNALISTA", "JUIZ", "LEILOEIRO", "LUTADOR", "MAESTRO", "MARCENEIRO", "MARINHEIRO", 
 "MATEMATICO", "MECANICO", "MEDICO", "METEOROLOGISTA", "MOTORISTA", "MUSICO", 
 "NUTRICIONISTA", "PALEONTÓLOGO", "PEDREIRO", "PILOTO", "PINTOR", "PSICOLOGO", 
 "PUBLICITARIO", "QUIMICO", "RECEPCIONISTA", "REPORTER", "ROTEIRISTA", "SEGURANÇA", 
 "SOLDADO", "TAXISTA", "TRADUTOR", "VENDEDOR", "VETERINARIO", "ZOÓLOGO",
 
 // Objetos
 "ABAJUR", "AGULHA", "ALMOFADA", "ARMARIO", "ASPIRADOR", "BANCO", "BANHEIRA", "BATERIA", 
 "BENGALA", "BICICLETA", "BINÓCULO", "BOLA", "BONECA", "BUZINA", "CADEIRA", "CADERNO", 
 "CAFETEIRA", "CAIXA", "CAMERA", "CANECA", "CANETA", "CAPACETE", "CELULAR", "CHAVE", 
 "CHICOTE", "CHOCALHO", "CHUPETA", "COLHER", "COMPUTADOR", "COPO", "DADO", "DESPERTADOR", 
 "DRONE", "ESCADA", "ESCOVA", "ESPADA", "ESPELHO", "ESPONJA", "ESTANTE", "FACA", 
 "FANTOCHE", "FAQUEIRO", "FERRAMENTA", "FILMADORA", "FLAUTA", "FOGAO", "FOGUETE", "FOLHA", 
 "FONE", "FORNO", "FRIGIDEIRA", "FURADEIRA", "GAITA", "GANCHO", "GARFO", "GELADEIRA", 
 "GLOBO", "GRAMPEADOR", "GUARDA-CHUVA", "GUITARRA", "HARPA", "IMPRESSORA", "INTERFONE", 
 "ISQUEIRO", "JANELA", "JARRA", "JOGO", "JORNAL", "LAMPADA", "LAPIS", "LIQUIDIFICADOR", 
 "LIVRO", "LUVA", "MACHADO", "MAQUINA", "MARTELO", "MESA", "MICROFONE", "MOEDA", "MONITOR", 
 "MOTO", "MOUSE", "NOTEBOOK", "OCULOS", "PANELA", "PAPEL", "PARAFUSO", "PENEIRA", "PERFUME", 
 "PIANO", "PINCEL", "PISTOLA", "PORTA", "PRATO", "QUADRO", "RADIO", "RALADOR", "REGUA", 
 "RELOGIO", "REMO", "REVISTA", "ROBO", "SABONETE", "SACO", "SECADOR", "SINO", "SOFA", 
 "TAMPA", "TAPETE", "TECLADO", "TELEFONE", "TELESCOPIO", "TELEVISAO", "TESOURA", "TIGELA", 
 "TOALHA", "TORNEIRA", "TRAVESSEIRO", "VASSOURA", "VELA", "VENTILADOR", "VIOLAO", "XADREZ", 
 "XICARA"
];
  export default palavras;
  